from model import send_excel_response

from flask import Response
import pytest



def test_send_excel_response():
    # Create a mock data payload (usually generated by Excel libraries).
    mock_data = b"Mock Excel Data"

    # Define a filename for testing.
    filename = "test_excel_file"

    # Call the function to get the response object.
    response = send_excel_response(mock_data, filename)

    # Assert that the response is an instance of Flask's Response.
    assert isinstance(response, Response)

    # Assert that the content type header is set to Excel format.
    assert response.headers["Content-Type"] == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

    # Assert that the Content-Disposition header includes the correct filename.
    expected_disposition = f"attachment; filename={filename}.xlsx"
    assert response.headers["Content-Disposition"] == expected_disposition