name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Initialize Python '3.x'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies and run tests (MatchedCountriesApplication)
      run: |
        cd applications/MatchedCountriesApplication
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pytest test_model.py

    - name: Build and Push Docker Images
      run: |
        docker build -t my-frontend-image ./applications/FrontEndApplication
        docker build -t my-matchedcountries-image ./applications/MatchedCountriesApplication
        docker build -t my-downloadfile-image ./applications/DownloadFileApplication
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push my-frontend-image
        docker push my-matchedcountries-image
        docker push my-downloadfile-image

    - name: Start Docker Compose Services
      run: |
        docker-compose -f docker-compose.yml up -d
